server:
# port: 8081
 servlet:
  context-path: /ylb
spring:
 profiles:
  active: dev
---
#  开发环境配置
spring:
 profiles: dev
 server:
 port: 8082
---
#  sit环境配置
spring:
 profiles: prod
 server:
  port: 8083
---
# uatt环境配置
spring:
 profiles: prod
 server:
  port: 8083