server:
  # port: 8081
  servlet:
    context-path: /ylb
spring:
  profiles:
    active: dev
person:
  name: yanlinbo
  age: 33
  sex: 男
  pets: [dog,cat,lion]
  cars:
    - jili
    - changan
    - changcheng
  maps: {k1: values1,k2: values2}
  girlfriend:
    name: yangyang
    age: 33
---
#  开发环境配置
spring:
  profiles: dev
server:
   port: 8082
---
#  sit环境配置
spring:
  profiles: sit
server:
  port: 8083
---
# uat环境配置
spring:
  profiles: uat
  server:
    port: 8083

